title: MySpace Windows 93 Themes
description: 💾 CSS themes made for profile customization on the site https://myspace.windows93.net/ ; a restored version of the old https://myspace.com/
url: "https://sophiezhng.github.io/my-space-windows-93-themes"
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: jekyll-theme-minimal
