title: MySpace Windows 93 Themes
description: 💾 CSS themes made for profile customization on myspace.windows93.net
url: "https://sophiezhng.github.io/my-space-windows-93-themes"
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: G-NETH5YXE1B
relative_links:
  enabled: true
  collections: true
  
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
theme: jekyll-theme-minimal
